"""Response capabilities consumed across independent application packages."""

from typing import Any, Protocol

from src.dss.domain.conversations.session import Session
from src.dss.domain.profiles.profile import UserProfile
from src.dss.domain.schemes.scheme import Scheme


class Responses(Protocol):
    def generate_greeting_response(self, language: str = "hi") -> str: ...
    def generate_farewell_response(self, language: str = "hi") -> str: ...
    def generate_no_schemes_response(self, language: str = "hi") -> str: ...
    def generate_scheme_selection_response(self, language: str = "hi") -> str: ...
    def generate_language_selection_response(self, language: str = "auto") -> str: ...

    def generate_help_response(
        self, language: str = "auto", *, has_active_scheme: bool = False,
    ) -> str: ...

    def generate_language_changed_response(
        self, language: str, *, has_active_scheme: bool = False,
    ) -> str: ...

    def generate_clarification_response(self, missing_field: str, language: str = "hi") -> str: ...
    def generate_field_reason_response(self, field: str, language: str = "hi") -> str: ...
    def generate_field_help_response(self, field: str, language: str = "hi") -> str: ...

    def generate_application_guidance(
        self, scheme_name: str, application_url: str | None, offline_process: str | None,
        application_steps: list[str] | None = None, processing_time: str | None = None,
        helpline_phone: str | None = None, language: str = "hi",
    ) -> str: ...

    async def generate_response(self, session: Session, context: dict[str, Any]) -> str: ...

    async def ensure_response_language(self, session: Session, text: str, language: str) -> str: ...

    async def translate_grounded_text_if_needed(
        self, session: Session, text: str, language: str,
    ) -> str: ...

    async def generate_scheme_question_response(
        self, session: Session, scheme: Scheme, profile: UserProfile,
        user_question: str, language: str, *, active_view: str | None = None,
    ) -> str: ...
